### High Order Terms?

    => higher order terms in linear models area 
    created when multiplying two or more x-variable by one another

    => 다차원 함수 라는 말 
    => 곡선이라는 말

### Interpreting Interactions 

    => x1* x2

## interpreting Coefficients

In [1]:
import numpy as np
import pandas as pd 
import statsmodels.api as sm;

df = pd.read_csv('./house_prices.csv')
df.head()

   house_id neighborhood  area  bedrooms  bathrooms      style    price
0      1112            B  1188         3          2      ranch   598291
1       491            B  3512         5          3  victorian  1744259
2      5952            B  1134         3          2      ranch   571669
3      3525            A  1940         4          2      ranch   493675
4      5108            B  2208         6          4  victorian  1101539

### Model 1. 
    => predict price using neighborhood, style, and area

In [2]:
df['neighborhood'].unique(), df['style'].unique()

(array(['B', 'A', 'C'], dtype=object),
 array(['ranch', 'victorian', 'lodge'], dtype=object))

In [3]:
dummies1_df = pd.get_dummies(df['neighborhood'])
dummies2_df = pd.get_dummies(df['style'])

new_df = df.join(dummies1_df)
new_df = new_df.join(dummies2_df)
new_df.head()

,house_id,neighborhood,area,bedrooms,bathrooms,style,price,A,B,C,lodge,ranch,victorian
0,1112,B,1188,3,2,ranch,598291,0,1,0,0,1,0
1,491,B,3512,5,3,victorian,1744259,0,1,0,0,0,1
2,5952,B,1134,3,2,ranch,571669,0,1,0,0,1,0
3,3525,A,1940,4,2,ranch,493675,1,0,0,0,1,0
4,5108,B,2208,6,4,victorian,1101539,0,1,0,0,0,1

In [4]:
new_df['intercept'] = 1

lm = sm.OLS(new_df['price'],new_df[['intercept','area','A','B','ranch','victorian']])
results = lm.fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.919
Model:                            OLS   Adj. R-squared:                  0.919
Method:                 Least Squares   F-statistic:                 1.372e+04
Date:                Tue, 14 Dec 2021   Prob (F-statistic):               0.00
Time:                        19:48:13   Log-Likelihood:                -80348.
No. Observations:                6028   AIC:                         1.607e+05
Df Residuals:                    6022   BIC:                         1.607e+05
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
intercept  -1.983e+05   5540.744    -35.791      0.000   -2.09e+05   -1.87e+05
area         348.7375      2.205    158.177      0.000     344.415     353.060
A           -194.2464   4965.459     -0.039      0.969   -9928.324    9539.832
B           5.243e+05   4687.484    111.844      0.000    5.15e+05    5.33e+05
ranch      -1974.7032   5757.527     -0.343      0.732   -1.33e+04    9312.111
victorian  -6262.7365   6893.293     -0.909      0.364   -1.98e+04    7250.586
==============================================================================
Omnibus:                      114.369   Durbin-Watson:                   2.002
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              139.082
Skew:                           0.271   Prob(JB):                     6.29e-31
Kurtosis:                       3.509   Cond. No.                     1.12e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.12e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

## model 2 

    => predict price 
    =>, using area , area squared
    => using style, 
    => not neighborhood

In [7]:
new_df['area_squared'] = new_df['area']*new_df['area']

In [8]:
new_df.head()

,house_id,neighborhood,area,bedrooms,bathrooms,style,price,A,B,C,lodge,ranch,victorian,intercept,area_squared
0,1112,B,1188,3,2,ranch,598291,0,1,0,0,1,0,1,1411344
1,491,B,3512,5,3,victorian,1744259,0,1,0,0,0,1,1,12334144
2,5952,B,1134,3,2,ranch,571669,0,1,0,0,1,0,1,1285956
3,3525,A,1940,4,2,ranch,493675,1,0,0,0,1,0,1,3763600
4,5108,B,2208,6,4,victorian,1101539,0,1,0,0,0,1,1,4875264

In [10]:
lm = sm.OLS(new_df['price'],new_df[['intercept','ranch','victorian','area','area_squared']])
results = lm.fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.678
Model:                            OLS   Adj. R-squared:                  0.678
Method:                 Least Squares   F-statistic:                     3173.
Date:                Tue, 14 Dec 2021   Prob (F-statistic):               0.00
Time:                        19:52:34   Log-Likelihood:                -84516.
No. Observations:                6028   AIC:                         1.690e+05
Df Residuals:                    6023   BIC:                         1.691e+05
Df Model:                           4
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
intercept     1.855e+04   1.26e+04      1.467      0.142   -6229.316    4.33e+04
ranch         9917.2547   1.27e+04      0.781      0.435    -1.5e+04    3.48e+04
victorian     2509.3957   1.53e+04      0.164      0.870   -2.75e+04    3.25e+04
area           334.0146     13.525     24.696      0.000     307.501     360.528
area_squared     0.0029      0.002      1.283      0.199      -0.002       0.007
==============================================================================
Omnibus:                      375.220   Durbin-Watson:                   2.009
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              340.688
Skew:                           0.519   Prob(JB):                     1.05e-74
Kurtosis:                       2.471   Cond. No.                     4.33e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.33e+07. This might indicate that there are
strong multicollinearity or other numerical problems.
"""